name: Migrate

on:
  push:
    branches:
      - main
    paths:
      - "internal/db/**"
  pull_request:
    paths:
      - "internal/db/**"

jobs:
  goose-migrate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v6
      - name: Install Goose
        uses: mscno/setup-goose@v1
        with:
          version: v3.26.0
      - name: Migrate up
        working-directory: internal/db/migrations
        run: |
          CONN="postgres://postgres:postgres@localhost:5432/postgres"
          goose postgres "$CONN" up
      - name: Migrate down
        working-directory: internal/db/migrations
        run: |
          CONN="postgres://postgres:postgres@localhost:5432/postgres"
          goose postgres "$CONN" down-to 0
